// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_cardapio_ru.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsCatracaoffline {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKWDk99UzmuKa7u-iu3ylPqJv16M_x9es',
    appId: '1:269166091811:web:ab3d73a626e2efd3b4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    authDomain: 'catracaoffline.firebaseapp.com',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
    measurementId: 'G-Y232RN8851',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMX8ZOq5AcHwgCzR-sOdKixVSZ49g5NQ',
    appId: '1:269166091811:android:1b4500514847ffedb4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2WqEpbeohXmDQpPuaJyZtre60g5TcP2E',
    appId: '1:269166091811:ios:446591febd2a6868b4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
    iosBundleId: 'br.uff.uffmobileplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2WqEpbeohXmDQpPuaJyZtre60g5TcP2E',
    appId: '1:269166091811:ios:446591febd2a6868b4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
    iosBundleId: 'br.uff.uffmobileplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKWDk99UzmuKa7u-iu3ylPqJv16M_x9es',
    appId: '1:269166091811:web:122c1ae5b0a21b2db4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    authDomain: 'catracaoffline.firebaseapp.com',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
    measurementId: 'G-TKWZG0XM2T',
  );
}
