// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsCatraca {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMX8ZOq5AcHwgCzR-sOdKixVSZ49g5NQ',
    appId: '1:269166091811:android:d7487b1247e3a6c8b4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2WqEpbeohXmDQpPuaJyZtre60g5TcP2E',
    appId: '1:269166091811:ios:29d20b3a70695c1bb4db96',
    messagingSenderId: '269166091811',
    projectId: 'catracaoffline',
    databaseURL: 'https://catracaoffline-default-rtdb.firebaseio.com',
    storageBucket: 'catracaoffline.firebasestorage.app',
    iosClientId:
        '269166091811-t64j4sq1ej9i1rt1j1p9lc5m6o4p1j9s.apps.googleusercontent.com',
    iosBundleId: 'br.uff.sti.uffmobileplus',
  );
}
