// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_tracking.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsTracking {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8L5bV9yU0Dwd-_WcCQV203ntDI0TeY8',
    appId: '1:937934866022:android:ae8b7d04863d0fb7a14fa7',
    messagingSenderId: '937934866022',
    projectId: 'umplus-monitora-uff',
    storageBucket: 'umplus-monitora-uff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8L5bV9yU0Dwd-_WcCQV203ntDI0TeY8',
    appId: '1:937934866022:ios:5c7b7d04863d0fb7a14fa7',
    messagingSenderId: '937934866022',
    projectId: 'umplus-monitora-uff',
    storageBucket: 'umplus-monitora-uff.firebasestorage.app',
    iosBundleId: 'br.uff.sti.uffmobileplus',
  );

  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    return android;
  }

  // Caso necessário adicione suporte para mais plataformas aqui usando como base os anteriores (android e ios).
}
