// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsHarpia {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwTG9iwUAMKdU2FUS3ecB5MXf7OkR2lIg',
    appId: '1:14422911132:web:ae815779d5d66516d96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    authDomain: 'harpia-c699b.firebaseapp.com',
    storageBucket: 'harpia-c699b.firebasestorage.app',
    measurementId: 'G-XEEC7NKGNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3OVRxW4KGnZUNhwB7TPL5zEMtByHFHI',
    appId: '1:14422911132:android:5748e5f1324e96abd96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    storageBucket: 'harpia-c699b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZySXBiQTei1bVZm2lhUDqep6XI3np1hA',
    appId: '1:14422911132:ios:a2bbd06f735889d8d96559',
    messagingSenderId: '14422911132',
    projectId: 'harpia-c699b',
    storageBucket: 'harpia-c699b.firebasestorage.app',
    androidClientId:
        '14422911132-ac5k471uuq6ajl62ge200i20sc9j6f74.apps.googleusercontent.com',
    iosClientId:
        '14422911132-inua5fm2k2l08785fs20vkfm5oun5bm8.apps.googleusercontent.com',
    iosBundleId: 'br.uff.sti.uffmobileplus',
  );
}
